### ISSUE TITLE
this makes me uncomfortable

### ISSUE THREAD

**Issue by WHEOfficial** [HarryXChen3/ecr_template#1]
i was born 4 minutes ago and my godfather showed me this code and i spontaneously combusted (i died 3 minutes ago) please remove the spontaneous combustors from your code

**Comment by HarryXChen3** [comment]
im sorry you feel this way, if you can point out where the causes of spontaneous combustion are in the source, that would help me identify the root cause of this issue.

thanks.

**Comment by WHEOfficial** [comment]
the spontaneous combustor was the lack of documentation. please document this and i will be born again.
